"""create_audit_events

Revision ID: c3e8a1f5d047
Revises: b7d41e0c9a52
Create Date: 2026-08-22 14:10:03.442918

Phase 1A Slice 3 (audit spine). Implements the table specified in
``project-governance/05-delivery/Phase1A_Foundation_Implementation_Plan.md``
section 8.1, closing the storage half of Phase 0 BLOCKER-1 ("there is no
audit trail -- not a weak one, none").

This migration creates storage only. **No call site writes to it yet**;
wiring denial and success events is Slices 4 and 5. Creating an empty
table changes no existing behaviour, which is why this slice is
zero-risk.

**No history is backfilled, and none can be.** Every row in this table
is an event this application observed after the table existed.
Synthesising rows for past operations would fabricate exactly the record
the table exists to make trustworthy.

Column choices that are not self-evident:

``recorded_seq`` is an identity column rather than the ``BIGSERIAL``
named in section 8.1. The two are the same mechanism -- an implicit
sequence with a column default -- but ``GENERATED BY DEFAULT AS
IDENTITY`` is the form SQLAlchemy models natively, so the ORM and the
migration agree without a hand-written server default. Its purpose and
its caveat are unchanged: it records insertion order **within one
database**, and gaps are expected and meaningless, because sequence
values are allocated outside the transaction and a rollback never
returns them. Section 8.6 explains at length why that property is
precisely what stops this column from being usable as a hash-chain
ordinal.

``organization_id`` is nullable, which is a deliberate exception to this
schema's tenant convention. A pre-tenant failure -- a malformed token, or
an authenticated identity with no provisioned ``public.users`` profile --
has no organization to attribute, and the alternative to a null is either
inventing a placeholder tenant or not recording the event at all. Both
are worse. A *business* event must never carry a null here; that is
application policy, enforced by ``AuditService``, not by this column.

``actor_user_id`` carries **no foreign key**, deliberately diverging from
every other table in this schema. Section 8.4: user rows are provisioned
and removed entirely outside this codebase, so ``NO ACTION`` would make a
user undeletable and ``CASCADE`` would delete audit history on user
deletion -- catastrophic for an audit trail. The actor is resolved at
read time, best-effort.

``occurred_at`` is ``TIMESTAMPTZ`` while the rest of the schema uses
naive ``TIMESTAMP`` (section 8.7). An audit timestamp whose offset is
ambiguous is not evidence.

``previous_state`` / ``new_state`` are ``JSONB`` but are never populated
from an entity's ``__dict__``. Section 8.5 mandates a per-object-type
allow-list plus a key denylist that raises on a forbidden key; both live
in ``app/services/audit.py``. The database cannot enforce that, so the
column type is permissive and the service is the control.

**Append-only status, stated honestly.** Section 8.2 specifies three
layers. This migration ships layers 1 and 2 only -- the repository
interface exposes no update or delete path, and the entity is frozen.
Layer 3 (``REVOKE UPDATE, DELETE, TRUNCATE``) is **not** executed here,
because it requires the name of the application's database role, and
that role is not recorded anywhere in this repository. Phase 0 section
5.2 (TB-5) observed the application connects with a role that bypasses
RLS, which suggests an owner or superuser-class role -- against which a
``REVOKE`` issued by that same role is ineffective anyway. Determining
the real role is the open Slice 3 investigation task named in section
8.2. Until it is answered, the accurate description of this table is
**append-only by application construction, not by database enforcement**,
and nothing in this codebase may call it immutable or tamper-evident.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'c3e8a1f5d047'
down_revision: Union[str, None] = 'b7d41e0c9a52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


ACTOR_TYPES = ('USER', 'SYSTEM', 'ANONYMOUS')
RESULTS = ('SUCCESS', 'DENIED', 'FAILED')


def upgrade() -> None:
    op.create_table(
        'audit_events',
        sa.Column(
            'id',
            postgresql.UUID(as_uuid=True),
            server_default=sa.text('gen_random_uuid()'),
            nullable=False,
        ),
        sa.Column(
            'recorded_seq',
            sa.BigInteger(),
            sa.Identity(always=False),
            nullable=False,
        ),
        sa.Column(
            'event_schema_version',
            sa.SmallInteger(),
            server_default=sa.text('1'),
            nullable=False,
        ),
        sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('actor_user_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('actor_type', sa.String(length=20), nullable=False),
        sa.Column('action', sa.String(length=100), nullable=False),
        sa.Column('object_type', sa.String(length=50), nullable=True),
        sa.Column('object_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('result', sa.String(length=20), nullable=False),
        sa.Column('previous_state', postgresql.JSONB(), nullable=True),
        sa.Column('new_state', postgresql.JSONB(), nullable=True),
        sa.Column('reason', sa.String(length=500), nullable=True),
        sa.Column('correlation_id', sa.String(length=64), nullable=False),
        sa.Column(
            'occurred_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('request_method', sa.String(length=10), nullable=True),
        sa.Column('request_path', sa.String(length=255), nullable=True),
        sa.Column('client_ip', postgresql.INET(), nullable=True),
        sa.Column('user_agent', sa.String(length=256), nullable=True),
        sa.PrimaryKeyConstraint('id', name='pk_audit_events'),
        sa.UniqueConstraint('recorded_seq', name='uq_audit_events_recorded_seq'),
        sa.CheckConstraint(
            "actor_type IN ('USER', 'SYSTEM', 'ANONYMOUS')",
            name='ck_audit_events_actor_type',
        ),
        sa.CheckConstraint(
            "result IN ('SUCCESS', 'DENIED', 'FAILED')",
            name='ck_audit_events_result',
        ),
        # A USER-attributed event with no actor id is unattributable, which
        # defeats the point of recording it.
        sa.CheckConstraint(
            "actor_type <> 'USER' OR actor_user_id IS NOT NULL",
            name='ck_audit_events_user_actor_has_id',
        ),
    )

    # Tenant-partitioned reverse-chronological read: the shape every
    # "what happened in my organization" query takes.
    op.create_index(
        'ix_audit_events_organization_occurred_at',
        'audit_events',
        ['organization_id', sa.text('occurred_at DESC')],
    )
    # "What happened to this object", across actions.
    op.create_index(
        'ix_audit_events_object',
        'audit_events',
        ['object_type', 'object_id'],
    )
    # Reassembling one request's full story from a log line's correlation id.
    op.create_index(
        'ix_audit_events_correlation_id',
        'audit_events',
        ['correlation_id'],
    )
    # "Every denial of this action, most recent first."
    op.create_index(
        'ix_audit_events_action_occurred_at',
        'audit_events',
        ['action', sa.text('occurred_at DESC')],
    )


def downgrade() -> None:
    # Dropping this table destroys audit history. It exists because Alembic
    # requires a reverse path and because the disposable CI test database
    # steps down as well as up; it must never be run against an instance
    # whose audit history is expected to be retained.
    op.drop_index('ix_audit_events_action_occurred_at', table_name='audit_events')
    op.drop_index('ix_audit_events_correlation_id', table_name='audit_events')
    op.drop_index('ix_audit_events_object', table_name='audit_events')
    op.drop_index('ix_audit_events_organization_occurred_at', table_name='audit_events')
    op.drop_table('audit_events')
