"""create_documents_table

Revision ID: eeb31636c877
Revises:
Create Date: 2026-07-07 12:45:29.622690

NOTE: ``engagement_id`` is intentionally left without a foreign key. The
live database already has an ``engagements`` table (and ``organizations``,
``users``, ``extracted_text``, ``ai_analysis_results``), but none of those
are yet represented in this repo's Alembic history -- they predate it /
were created out-of-band. Adding the FK here would make this migration
depend on a table it doesn't itself create, and would fail against a
genuinely fresh database. Deferred until a dedicated schema-reconciliation
migration brings all of those tables under Alembic control.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'eeb31636c877'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('processing_status', sa.String(), nullable=False),
    sa.Column('engagement_id', sa.UUID(), nullable=False),  # no FK yet -- see module note
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_path')
    )
    op.create_index(op.f('ix_documents_engagement_id'), 'documents', ['engagement_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_engagement_id'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
